### ISSUE TITLE
Capistranoができない

### ISSUE THREAD

**Issue by 1noseA** [1noseA/minimal-closet#72]
Capistranoをカリキュラム通りに進め、最後の
 bundle exec cap production deployで
#<Thread:0x0000560d82108f20@/var/lib/gems/2.5.0/gems/sshkit-1.21.0/lib/sshkit/runners/parallel.rb:10 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	1: from /var/lib/gems/2.5.0/gems/sshkit-1.21.0/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
/var/lib/gems/2.5.0/gems/sshkit-1.21.0/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute': Exception while executing as ec2-user@18.178.164.47: Authentication failed for user ec2-user@18.178.164.47 (SSHKit::Runner::ExecuteError)
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as ec2-user@18.178.164.47: Authentication failed for user ec2-user@18.178.164.47

Caused by:
Net::SSH::AuthenticationFailed: Authentication failed for user ec2-user@18.178.164.47

Tasks: TOP => rbenv:validate
(See full trace by running task with --trace)
というエラーになってしまった。
カリキュラムではエラーについて
OpenSSH keys only supported if ED25519 is available
の対策しか書かれていないが、
SSHKit::Runner::ExecuteErrorのエラーも検索すると結構出てくるので
この対策についても書いていただけると嬉しい。

**Comment by 1noseA** [comment]
SSHKit::Runner::ExecuteErrorに関して
再起動するとSSH鍵が消えてしまうみたいなので .sshディレクトリにて以下のコマンドでSSH鍵を登録し直すという対策が見つかり、
ssh-add ~/.ssh/practice-aws.pem
を再度やってみたが同様のエラー。
最初に間違えてvagrantでeval `ssh-agent`やったのがよくなかったのか。
sshとか鍵系は一人でやるには難しそうなので諦める。
killしてデプロイし直したらcssが反映されないし、ログアウトができない。

**Comment by 1noseA** [comment]
GitHubにプッシュした直前のコミット[Add]capistranoを
git reset --hard HEAD^
コマンドで直前のコミットを消し、
git push origin +master
で強制プッシュ。
そうしてもcssが反映されない。
viで編集した部分も戻さなきゃいけないのか？と考える。

**Comment by 1noseA** [comment]
https://qiita.com/KONTA2019/items/2a519f18b204dea9a771
この記事により、原因が
ec2上のetc/nginx/conf.d/rails.confの記述内容の参照先の誤りにより、
/var/www/アプリ名/public/assetとすべきところを
/var/www/アプリ名/current/public/assetとしていたため
と知り、Capistranoでviで追加したcurrentの2箇所消した。
その後killして起動し直したら元どおり反映されるようになった。
